### ISSUE TITLE
Dependency issue with ember-invoke-action

### ISSUE THREAD

**Issue by km-smith** [scoutforpets/ember-timepicker#2]
After installing the addon with ember install the component does not work due to unresolved module import.

`Could not find module 'ember-invoke-action' imported from 'ember-timepicker/components/ember-timepicker'`

Should probably stick to this.send to trigger actions since fewer dependencies the better IMO.

https://github.com/scoutforpets/ember-timepicker/blob/2b27e0f689b522ef524224b949f4a4b0419bd2ea/package.json#L48

**Comment by jamesdixon** [comment]
Hello, there was an outstanding PR that I just merged that should take care of this. You can pull from master for the time being until I have some to publish to NPM. When I do, I'll take a look at removing ember-invoke-action.

**Comment by km-smith** [comment]
The company I work for needs things published to npm so we can verify licenses and duplicate the packages inside our network so I'll need to wait until you publish to verify. I can send you a PR to remove the dependency as I've done it locally to continue working.

**Comment by jamesdixon** [comment]
removed in  d532c33
