### ISSUE TITLE
No time option is working or taken into account

### ISSUE THREAD

**Issue by belgoros** [scoutforpets/ember-timepicker#4]
I tried to add some options as described at [jQuery timepicker docs](http://timepicker.co/options/), as follows:
```
# templates/working-hours.hbs

{{ember-timepicker
    onChange=(action 'onChange')
    timeFormat='HH:mm'
}}
```
and it does not work. I have always the times from `12:00 AM to 11:30 PM` displayed instead of 09:00, 17:00, etc.. What's wrong with that ? No matter the option I take, it does not work either:
```
# templates/working-hours.hbs

{{ember-timepicker
    onChange=(action 'onChange')
    timeFormat='HH:mm'
    minTime='05:00'
   ... etc.
}}
```
My Ember and node versions:
```
ember-cli: 3.0.0
node: 8.9.1
os: darwin x64
```
I'm also using [ember-cli-bootstrap-4](https://github.com/kaermorchen/ember-cli-bootstrap-4)

**Comment by loqtor** [comment]
Hey man,

Not sure if you worked this out, but you should pass an object as the options through an `options` attribute.

```
{{ember-timepicker
  onChange=(action 'onChange')
  options=options
}}
```

I hope that helps.

Cheers!

**Comment by belgoros** [comment]
@loqtor Could you give an example on how to pass in `options` to have the time format as follows:
```
timeFormat='HH:mm'
minTime='05:00'
```
Here is what I have in `posts/new.js` controller:
```
import Controller from '@ember/controller';

export default Controller.extend({
  options: {
    dropdown: false
  },

  actions: {
    onChange(selectedTime) {
      console.log(selectedTime);
    }
  }
});
```
In `app/router.js`:
```
Router.map(function() {
  this.route('posts', function() {
    this.route('new');
    this.route('post', { path: ':id' }, function() {
      this.route('comments');
    });
  });
});
```
In the `posts/new.hbs` template:
```
{{ember-timepicker
  onChange=(action 'onChange')
  options=options
}}
```
In `templates/posts.hbs` template:
```
<div class='row'>
  <h3>Posts lists</h3>
</div>
<div class='row'>
  <ul>
    {{#each model as |post|}}
      <li>{{post.title}}</li>
    {{/each}}
  </ul>
</div>
{{#link-to 'posts.new'}}New post{{/link-to}}
{{outlet}}

```

When clicking on *New post*  link I have the error:
```
loader.js:247 Uncaught Error: Could not find module `ember-invoke-action` imported from `ember-timepicker/components/ember-timepicker`
    at missingModule (loader.js:247)
    at findModule (loader.js:258)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at Module.findDeps (loader.js:168)
    at findModule (loader.js:262)
    at requireModule (loader.js:24)
    at Class._extractDefaultExport (index.js:410)
    at Class.resolveOther (index.js:110)
    at Class.superWrapper [as resolveOther] (ember-utils.js:428)
```
More of that, there is an error when starting the server pointing to the way to declare `options` in the controller:
```
/.../controllers/posts/new.js
   4:3  error  Only string, number, symbol, boolean, null, undefined, and function are allowed as default properties  ember/avoid-leaking-state-in-ember-objects
```

It seems like nothing works at all :(.
Thank you.

**Comment by loqtor** [comment]
Hey @belgoros,

I’m using an old version of Ember. I’m on 2.13 on the project I used this addon for.

Other than that the example you posted is exactly what I’m doing and it just works for me.

Just out of curiosity, have you tried to manually install `ember-invoke-action`?
I know it should not make sense, but just to see if that does it. 😊

Cheers!

**Comment by belgoros** [comment]
@loqtor [ember-invoke-action](https://github.com/martndemus/ember-invoke-action) is not maintained anymore, so the answer will _nope_.

**Comment by loqtor** [comment]
Ok. Not sure how to help you then.

But since you are worried about that non maintained package, maybe you should not use this at all. 😊

To be honest, I thought of doing this same thing myself (it’s almost just a dropdown with options for hours). But I just leaned towards using _someone else’s wheel_.

I hope you can work it out.

Cheers!

**Comment by jamesdixon** [comment]
@belgoros I wasn't able to reproduce this, unfortunately. Also, v0.3.0 was just released and removed `ember-invoke-action`
